### PR TITLE
Added new Feature "Customizable AuthYkValidationProtocol AuthYkValidationHost"

### PR DESCRIPTION
**Pull request by offlinehoster**
Now you can configure your own protocol (http/https/…) and your own host where your validation auth service is running.

### CODE REVIEW

**Comment by pquerna** [comment]
I'm on vacation for the next week, but will try to hit this up when I get a few.  Thanks for the patch.

**Comment by offlinehoster** [comment]
I hope you enjoyed your vacation ;)

What do you think about a merge right now ;) ?

Cheers
Christian

**Comment by offlinehoster** [comment]
Long time no patch ;)

**Comment by offlinehoster** [comment]
nothing new here?

**Comment by pquerna** [comment]
Hi @offlinehoster, I've merged your PR and added you as a collaborator. Thank you!

**Comment by offlinehoster** [comment]
Thanks @pquerna

**Pull request merged**
